ACHIEVEMENTS = {
    "first_message": {
        "name": "Первые слова",
        "description": "Отправьте первое сообщение на сервере",
        "reward": 100,
        "icon": "💭",
        "category": "social",
        "requirements": {"messages_clean": 1},
    },
    "ten_messages": {  
        "name": "Начинающий",
        "description": "Отправить 10 сообщений",
        "reward": 250,
        "icon": "💬",
        "category": "social",
        "requirements": {"messages_clean": 10},
    },
    "fifty_messages": {  
        "name": "Активный",
        "description": "Отправить 50 сообщений",
        "reward": 500,
        "icon": "📝",
        "category": "social",
        "requirements": {"messages_clean": 50},
    },
    "hundred_messages": {
        "name": "Разговорчивый",
        "description": "Отправить 100 сообщений",
        "reward": 1000,
        "icon": "📨",
        "category": "social",
        "requirements": {"messages_clean": 100},
    },
    "thousand_messages": {
        "name": "Болтун",
        "description": "Отправить 1000 сообщений",
        "reward": 2500,
        "icon": "📬",
        "category": "social",
        "requirements": {"messages_clean": 1000},
    },
    "ten_thousand_messages": {
        "name": "Говорун года",
        "description": "Отправить 10000 сообщений",
        "reward": 10000,
        "icon": "📮",
        "category": "social",
        "requirements": {"messages_clean": 10000},
    },
    "level_five": {
        "name": "Опытный",
        "description": "Достигнуть 5 уровня",
        "reward": 1000,
        "icon": "📈",
        "category": "progression",
        "requirements": {"level": 5},
    },
    "level_ten": {
        "name": "Профессионал",
        "description": "Достигнуть 10 уровня",
        "reward": 2500,
        "icon": "⭐",
        "category": "progression",
        "requirements": {"level": 10},
    },
    "level_twenty": {
        "name": "Мастер",
        "description": "Достигнуть 20 уровня",
        "reward": 5000,
        "icon": "🌟",
        "category": "progression",
        "requirements": {"level": 20},
    },
    "level_fifty": {
        "name": "Легенда",
        "description": "Достигнуть 50 уровня",
        "reward": 15000,
        "icon": "👑",
        "category": "progression",
        "requirements": {"level": 50},
    },
    "voice_hour": {
        "name": "Голосовой чемпион",
        "description": "Провести 1 час в голосовом канале",
        "reward": 500,
        "icon": "🎤",
        "category": "voice",
        "requirements": {"voice_hours": 1},
    },
    "voice_ten_hours": {
        "name": "Радиоведущий",
        "description": "Провести 10 часов в голосовых каналах",
        "reward": 2000,
        "icon": "🎙️",
        "category": "voice",
        "requirements": {"voice_hours": 10},
    },
    "voice_hundred_hours": {
        "name": "Голосовая легенда",
        "description": "Провести 100 часов в голосовых каналах",
        "reward": 10000,
        "icon": "🔊",
        "category": "voice",
        "requirements": {"voice_hours": 100},
    },
    "first_marriage": {
        "name": "Счастливы вместе",
        "description": "Вступить в брак",
        "reward": 2000,
        "icon": "❤️",
        "category": "social",
    },
}

